platform :ios, ‘8.0’

target “addsou” do
pod 'SDWebImage'
pod ‘RESideMenu’
pod ‘Masonry’
pod ‘MBProgressHUD’
pod ‘MJExtension’
pod ‘MJRefresh’
pod ‘AFNetworking’
pod 'FMDB'
pod 'UMengAnalytics'
pod 'SSKeychain'

end