platform :ios, ‘8.0’
# ruby语法
# target数组 如果有新的target直接加入该数组
targetsArray = [‘addsou’, ‘addsouVoice’]
# 循环
targetsArray.each do |t|
    target t do
        pod 'SDWebImage'
        pod ‘RESideMenu’
        pod ‘Masonry’
        pod ‘MBProgressHUD’
        pod ‘MJExtension’
        pod ‘MJRefresh’
        pod ‘AFNetworking’
        pod 'FMDB'
        pod 'UMengAnalytics'
        pod 'SSKeychain'
        pod 'iCarousel'
        pod 'LSStatusBarHUD'
    end
end
